
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kathir
 */
public class Payment2 extends javax.swing.JFrame {

    /**
     * Creates new form Payment2
     */
    public Payment2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jRadioButton1.setText("Credit Card");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(30, 200, 120, 29);

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jRadioButton2.setText("Debit Card");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(30, 230, 120, 29);

        jLabel4.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel4.setText("Name Of The Card");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 310, 140, 20);

        jLabel5.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel5.setText("Card Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 340, 100, 20);

        jLabel6.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel6.setText("Expiry Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 370, 100, 20);

        jTextField1.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jTextField1.setEnabled(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(190, 310, 110, 24);

        jTextField2.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jTextField2.setEnabled(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(190, 340, 110, 24);

        jTextField3.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jTextField3.setEnabled(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(190, 370, 110, 24);

        jLabel7.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel7.setText("Grand Total :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 220, 110, 20);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(420, 220, 90, 23);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jButton4.setText("Total Amount");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(350, 260, 140, 29);

        jLabel2.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel2.setText("Mode Of Payment");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 170, 120, 20);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jButton3.setText("Pay");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 430, 70, 30);

        jLabel1.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel1.setText("Booked In Name Of :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 170, 160, 20);

        jTextField5.setBackground(new java.awt.Color(240, 240, 240));
        jTextField5.setBorder(null);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(420, 170, 120, 30);

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setText("Payment For Meeting And Events");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 120, 340, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-15.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 0, 170, 110);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 580, 510);

        setSize(new java.awt.Dimension(597, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"please fill in the card details");
        if(jRadioButton2.isSelected()==true)
        {
            jTextField1.setEnabled(false);
            jTextField3.setEnabled(false);
            jTextField2.setEnabled(false);
        }
        else
        {
            jTextField1.setEnabled(true);
            jTextField3.setEnabled(true);
            jTextField2.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"please fill in the card details");
        if(jRadioButton1.isSelected()==true)
        {
            jTextField1.setEnabled(false);
            jTextField3.setEnabled(false);
            jTextField2.setEnabled(false);
        }
        else
        {
            jTextField1.setEnabled(true);
            jTextField3.setEnabled(true);
            jTextField2.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String name = jTextField5.getText();
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:"
                    + "mysql://localhost:3306/katpro","root","123");
            Statement s =(Statement)con.createStatement();
            String q ="select minamount from meetevent where name='"+name+"';";
            ResultSet rs = s.executeQuery(q);
            int x = 0;
            while(rs.next())
            {
                int tot=rs.getInt("minamount");
                jTextField4.setText(""+tot);
                x++;
            }
            if(x==0)
             JOptionPane.showMessageDialog(null,"Record not found for the "
                     + "given name. Check the name.");
            else
            {
             JOptionPane.showMessageDialog(null,"Grand Total Of Your Reservation");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String amt = jTextField4.getText();
        if(jRadioButton1.isSelected()==true||jRadioButton2.isSelected()==true)
        {
            if(amt.length()==0)
               JOptionPane.showMessageDialog(null,"Get the amount payable"
                       + " by entering your boooked-in name !");
            else if(jTextField1.getText().length()==0||jTextField2.getText()
                    .length()==0||jTextField3.getText().length()==0)
               JOptionPane.showMessageDialog(null,"Enter your card details "
                       + "properly" );
            else
            {
                JOptionPane.showMessageDialog(null,"Payment successful");
                new ThankYou().setVisible(true);
                this.dispose();
            }
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Select Mode of Payment");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
